services:
  web:
    build: .
    ports:
      - "81:8000"
    volumes:
      - ./pro_caida:/code
      - ./scripts_docker:/scripts_docker
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: bd-caida
      DATABASE_USER: alberto
      DATABASE_PASSWORD: 1234

  db:
    image: postgres:15
    container_name: bd-postgres
    environment:
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bd-caida
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: