services:
  db:
    image: postgres:15
    container_name: bd-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bd-caida
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    ports:
      - "81:8000"
    volumes:
      - ./pro_caida:/code
      - ./scripts_docker:/scripts_docker
    depends_on:
      - db
